### PR TITLE
Update checkstyle and add unused import check

### PR DESCRIPTION
**Pull request by bennetelli**
just saw that there are some unused imports and we don't have a checkstyle check for it because there was a bug in the checkstyle version we used. So I updated checkstyle to a version where this issue is fixed (see: https://github.com/checkstyle/checkstyle/issues/2840)

### CODE REVIEW

**Comment by bennetelli** [comment]
btw: why do we want to meet the ActiveMQ coding guidelines? 

There is a comment in the camel-checkstyle.xml: "Checks to make sure the code meets the ActiveMQ coding guidelines..."

**Comment by davsclaus** [comment]
@bennetelli yeah that was a copy, so you can change the name to Apache Camel instead of AMQ

**Comment by bennetelli** [comment]
@davsclaus and what about the source camel-checkstyle.xml in https://github.com/apache/camel/tree/master/buildingtools ?

**Comment by davsclaus** [comment]
Yeah sure you are welcome to provide a PR for that

**Pull request merged**
